/*
 * input_policy_host_test.cpp -- F1: verificacion host del catalogo dorado
 * de input del port (ActionMap + ChordResolver).
 *
 * Compila sin dependencias de la app: g++ -std=gnu++03 -Wall -Wextra -Werror
 *   ChordResolver.cpp ActionMap.cpp input_policy_host_test.cpp
 *
 * Cada assertion es una transcripcion del comportamiento del codigo dorado
 * (SampleChopperModal.cpp ProcessButtonMask, MixerView.cpp ProcessButtonMask,
 * AppWindow.cpp onEvent/SynchronizeInputMask en Bacon 1.2.1). Si falla,
 * ALGUIEN CAMBIO EL COMPORTAMIENTO o el catalogo no lo transcribe.
 */
#include <stdio.h>
#include "Application/UI/Input/ChordResolver.h"

using namespace UI::Input;

static int g_failures = 0;

#define CHECK(cond) do { \
    if (!(cond)) { \
        printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        ++g_failures; \
    } \
} while (0)

#define EXPECT_ACTION(mask_, ctx_, action_) do { \
    ActionId got = ChordResolver_Resolve((mask_), (ctx_)); \
    if (got != (action_)) { \
        printf("FAIL %s:%d: mask=0x%04x ctx=%d esperaba %d got %d\n", \
               __FILE__, __LINE__, (unsigned)(mask_), (int)(ctx_), \
               (int)(action_), (int)got); \
        ++g_failures; \
    } \
} while (0)

static void test_global(void) {
    EXPECT_ACTION(KEY_SELECT | KEY_R1, CTX_GLOBAL, ACTION_OPEN_HELP);
    EXPECT_ACTION(KEY_SELECT | KEY_R1 | KEY_A, CTX_GLOBAL, ACTION_OPEN_HELP);
    EXPECT_ACTION(KEY_SELECT | KEY_R2, CTX_GLOBAL, ACTION_OPEN_AUDIO_DRIVER);
    EXPECT_ACTION(KEY_L1 | KEY_X, CTX_GLOBAL, ACTION_UNDO);
    EXPECT_ACTION(KEY_R1 | KEY_X, CTX_GLOBAL, ACTION_REDO);
    /* L1+R1+X: la tabla no lo resuelve (regla V16 de AppWindow). */
    EXPECT_ACTION(KEY_L1 | KEY_R1 | KEY_X, CTX_GLOBAL, ACTION_NONE);
    EXPECT_ACTION(KEY_L1, CTX_GLOBAL, ACTION_NONE);
    EXPECT_ACTION(KEY_A | KEY_B, CTX_GLOBAL, ACTION_NONE);
    printf("global: help/audio/undo/redo OK\n");
}

static void test_mixer(void) {
    /* REQ: L1+A -> menu en Mixer, exactamente igual. */
    EXPECT_ACTION(KEY_L1 | KEY_A, CTX_MIXER, ACTION_OPEN_MENU);
    EXPECT_ACTION(KEY_L1 | KEY_A | KEY_UP, CTX_MIXER, ACTION_VOLUME_COARSE_UP);
    EXPECT_ACTION(KEY_L1 | KEY_A | KEY_L2, CTX_MIXER, ACTION_NONE);

    EXPECT_ACTION(KEY_R2 | KEY_A, CTX_MIXER, ACTION_OPEN_INSTRUMENT_FX);
    EXPECT_ACTION(KEY_R2 | KEY_B, CTX_MIXER, ACTION_CYCLE_FX_EDIT_TARGET);
    EXPECT_ACTION(KEY_R2 | KEY_UP, CTX_MIXER, ACTION_CYCLE_FX_EDIT_TARGET);
    EXPECT_ACTION(KEY_R2 | KEY_A | KEY_UP, CTX_MIXER, ACTION_OPEN_INSTRUMENT_FX);

    EXPECT_ACTION(KEY_L2 | KEY_A | KEY_B, CTX_MIXER, ACTION_RESET_PAN);
    EXPECT_ACTION(KEY_L2 | KEY_A | KEY_LEFT, CTX_MIXER, ACTION_PAN_NUDGE_LEFT_COARSE);
    EXPECT_ACTION(KEY_L2 | KEY_LEFT, CTX_MIXER, ACTION_PAN_NUDGE_LEFT);
    EXPECT_ACTION(KEY_L2 | KEY_UP, CTX_MIXER, ACTION_NONE);
    EXPECT_ACTION(KEY_L2 | KEY_LEFT | KEY_UP, CTX_MIXER, ACTION_PAN_NUDGE_LEFT);

    EXPECT_ACTION(KEY_A | KEY_UP, CTX_MIXER, ACTION_VOLUME_COARSE_UP);
    EXPECT_ACTION(KEY_A | KEY_DOWN, CTX_MIXER, ACTION_VOLUME_COARSE_DOWN);
    EXPECT_ACTION(KEY_A | KEY_LEFT, CTX_MIXER, ACTION_VOLUME_FINE_DECREASE);
    EXPECT_ACTION(KEY_L1 | KEY_UP, CTX_MIXER, ACTION_VOLUME_COARSE_UP);
    EXPECT_ACTION(KEY_L1 | KEY_LEFT, CTX_MIXER, ACTION_MIX_CURSOR_LEFT);
    EXPECT_ACTION(KEY_UP, CTX_MIXER, ACTION_VOLUME_FINE_UP);
    EXPECT_ACTION(KEY_LEFT, CTX_MIXER, ACTION_MIX_CURSOR_LEFT);
    EXPECT_ACTION(KEY_START, CTX_MIXER, ACTION_PLAY_STOP);
    EXPECT_ACTION(KEY_START | KEY_UP, CTX_MIXER, ACTION_PLAY_STOP);
    EXPECT_ACTION(KEY_L2 | KEY_A | KEY_UP, CTX_MIXER, ACTION_NONE);
    printf("mixer MIX: menu, pan, volumen, cursor OK\n");
}

static void test_mixer_fx(void) {
    EXPECT_ACTION(KEY_R2 | KEY_A, CTX_MIXER_FX, ACTION_OPEN_INSTRUMENT_FX);
    EXPECT_ACTION(KEY_R2, CTX_MIXER_FX, ACTION_NONE);
    EXPECT_ACTION(KEY_R2 | KEY_UP, CTX_MIXER_FX, ACTION_NONE);
    EXPECT_ACTION(KEY_A | KEY_B, CTX_MIXER_FX, ACTION_RESET_PARAMETER);
    EXPECT_ACTION(KEY_A | KEY_B | KEY_UP, CTX_MIXER_FX, ACTION_EDIT_PARAM_UP);
    EXPECT_ACTION(KEY_A | KEY_UP, CTX_MIXER_FX, ACTION_EDIT_PARAM_UP);
    EXPECT_ACTION(KEY_A | KEY_LEFT, CTX_MIXER_FX, ACTION_EDIT_PARAM_LEFT);
    EXPECT_ACTION(KEY_UP, CTX_MIXER_FX, ACTION_ROW_UP);
    EXPECT_ACTION(KEY_DOWN, CTX_MIXER_FX, ACTION_ROW_DOWN);
    EXPECT_ACTION(KEY_LEFT, CTX_MIXER_FX, ACTION_EDIT_PARAM_LEFT);
    EXPECT_ACTION(KEY_START, CTX_MIXER_FX, ACTION_PLAY_STOP);
    EXPECT_ACTION(KEY_L2 | KEY_UP, CTX_MIXER_FX, ACTION_NONE);
    printf("mixer FX pages: reset, edit, filas OK\n");
}

static void test_chopper_main(void) {
    EXPECT_ACTION(KEY_L1 | KEY_X, CTX_CHOPPER, ACTION_UNDO);
    EXPECT_ACTION(KEY_R1 | KEY_X, CTX_CHOPPER, ACTION_REDO);
    EXPECT_ACTION(KEY_L1 | KEY_R1, CTX_CHOPPER, ACTION_TOGGLE_PITCH_MODE);
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER, ACTION_SPLIT_PARTS);
    EXPECT_ACTION(KEY_R1 | KEY_B, CTX_CHOPPER, ACTION_CLOSE);
    EXPECT_ACTION(KEY_L2 | KEY_B, CTX_CHOPPER, ACTION_STOP_PREVIEW);
    EXPECT_ACTION(KEY_SELECT, CTX_CHOPPER, ACTION_TOGGLE_TRIM_MODE);
    EXPECT_ACTION(KEY_R1 | KEY_A, CTX_CHOPPER, ACTION_AUTOSAVE_CHOPS);
    EXPECT_ACTION(KEY_R1 | KEY_LEFT, CTX_CHOPPER, ACTION_SELECT_PREV_SAMPLE);
    EXPECT_ACTION(KEY_R1 | KEY_RIGHT, CTX_CHOPPER, ACTION_SELECT_NEXT_SAMPLE);
    EXPECT_ACTION(KEY_R2 | KEY_A, CTX_CHOPPER, ACTION_PLAY_FULL);
    EXPECT_ACTION(KEY_R2 | KEY_LEFT, CTX_CHOPPER, ACTION_SELECT_PREV_CHOP);
    EXPECT_ACTION(KEY_R2 | KEY_RIGHT, CTX_CHOPPER, ACTION_SELECT_NEXT_CHOP);
    EXPECT_ACTION(KEY_Y, CTX_CHOPPER, ACTION_DELETE_CHOP);
    EXPECT_ACTION(KEY_B, CTX_CHOPPER, ACTION_PLAY_CHOP_PREVIEW);
    EXPECT_ACTION(KEY_A, CTX_CHOPPER, ACTION_ADD_CHOP);
    EXPECT_ACTION(KEY_A | KEY_SELECT, CTX_CHOPPER, ACTION_ADD_CHOP);
    EXPECT_ACTION(KEY_X | KEY_B, CTX_CHOPPER, ACTION_PLAY_CHOP_PREVIEW);
    EXPECT_ACTION(KEY_LEFT, CTX_CHOPPER, ACTION_NUDGE_CURSOR_LEFT);
    EXPECT_ACTION(KEY_L1 | KEY_RIGHT, CTX_CHOPPER, ACTION_NUDGE_CURSOR_RIGHT_COARSE);
    EXPECT_ACTION(KEY_UP, CTX_CHOPPER, ACTION_ZOOM_IN);
    EXPECT_ACTION(KEY_L1 | KEY_DOWN, CTX_CHOPPER, ACTION_ZOOM_OUT_COARSE);
    EXPECT_ACTION(KEY_X, CTX_CHOPPER, ACTION_NONE);
    EXPECT_ACTION(KEY_L1 | KEY_A, CTX_CHOPPER, ACTION_NONE);
    EXPECT_ACTION(KEY_L1, CTX_CHOPPER, ACTION_NONE);
    EXPECT_ACTION(KEY_R2 | KEY_B, CTX_CHOPPER, ACTION_NONE);
    printf("chopper MAIN: undo/redo, split, close, preview/apply, cursor/zoom OK\n");
}

static void test_chopper_trim(void) {
    EXPECT_ACTION(KEY_L1 | KEY_X, CTX_CHOPPER_TRIM, ACTION_UNDO);
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER_TRIM, ACTION_SNAP_BOUNDARY_END);
    EXPECT_ACTION(KEY_L1 | KEY_A, CTX_CHOPPER_TRIM, ACTION_SNAP_BOUNDARY_START);
    EXPECT_ACTION(KEY_R2 | KEY_Y, CTX_CHOPPER_TRIM, ACTION_NORMALIZE);
    /* R2+Y con flecha: el golden no normaliza (la rama exige pureza) y el
     * acorde CAE a la rama de zoom/nudge: UP -> zoom (fidelidad de orden). */
    EXPECT_ACTION(KEY_R2 | KEY_Y | KEY_UP, CTX_CHOPPER_TRIM, ACTION_ZOOM_IN);
    EXPECT_ACTION(KEY_R2 | KEY_Y | KEY_RIGHT, CTX_CHOPPER_TRIM, ACTION_SELECT_NEXT_CHOP);
    EXPECT_ACTION(KEY_R1 | KEY_A, CTX_CHOPPER_TRIM, ACTION_CROP);
    EXPECT_ACTION(KEY_L2 | KEY_Y, CTX_CHOPPER_TRIM, ACTION_DELETE_RANGE);
    EXPECT_ACTION(KEY_A | KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_START_LEFT);
    EXPECT_ACTION(KEY_L1 | KEY_A | KEY_RIGHT, CTX_CHOPPER_TRIM, ACTION_NUDGE_START_RIGHT_COARSE);
    EXPECT_ACTION(KEY_B | KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_END_LEFT);
    EXPECT_ACTION(KEY_L1 | KEY_B | KEY_RIGHT, CTX_CHOPPER_TRIM, ACTION_NUDGE_END_RIGHT_COARSE);
    EXPECT_ACTION(KEY_Y, CTX_CHOPPER_TRIM, ACTION_TRIM_PREVIEW_START);
    EXPECT_ACTION(KEY_Y | KEY_X, CTX_CHOPPER_TRIM, ACTION_NONE);
    EXPECT_ACTION(KEY_X, CTX_CHOPPER_TRIM, ACTION_TRIM_PREVIEW_END);
    EXPECT_ACTION(KEY_B, CTX_CHOPPER_TRIM, ACTION_NONE);
    EXPECT_ACTION(KEY_A, CTX_CHOPPER_TRIM, ACTION_NONE);
    EXPECT_ACTION(KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_CURSOR_LEFT);
    printf("chopper TRIM: snap, crop, delete, normalize, nudges OK\n");
}

static void test_chopper_pitch(void) {
    /* REQ: B -> Preview, A -> Apply en Pitch, exactamente igual. */
    EXPECT_ACTION(KEY_B, CTX_CHOPPER_PITCH, ACTION_PITCH_PREVIEW);
    EXPECT_ACTION(KEY_A, CTX_CHOPPER_PITCH, ACTION_PITCH_APPLY);
    EXPECT_ACTION(KEY_A | KEY_B, CTX_CHOPPER_PITCH, ACTION_NONE);

    EXPECT_ACTION(KEY_L1 | KEY_X, CTX_CHOPPER_PITCH, ACTION_UNDO);
    EXPECT_ACTION(KEY_R1 | KEY_X, CTX_CHOPPER_PITCH, ACTION_REDO);
    EXPECT_ACTION(KEY_L1 | KEY_R1, CTX_CHOPPER_PITCH, ACTION_TOGGLE_PITCH_MODE);
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER_PITCH, ACTION_SPLIT_PARTS);
    EXPECT_ACTION(KEY_L2 | KEY_B, CTX_CHOPPER_PITCH, ACTION_STOP_PREVIEW);
    EXPECT_ACTION(KEY_R2 | KEY_LEFT, CTX_CHOPPER_PITCH, ACTION_PITCH_SCOPE_PREV);
    EXPECT_ACTION(KEY_R2 | KEY_RIGHT, CTX_CHOPPER_PITCH, ACTION_PITCH_SCOPE_NEXT);
    EXPECT_ACTION(KEY_DOWN, CTX_CHOPPER_PITCH, ACTION_PITCH_PARAM_NEXT);
    EXPECT_ACTION(KEY_UP, CTX_CHOPPER_PITCH, ACTION_PITCH_PARAM_PREV);
    EXPECT_ACTION(KEY_RIGHT, CTX_CHOPPER_PITCH, ACTION_PITCH_VALUE_UP);
    EXPECT_ACTION(KEY_LEFT, CTX_CHOPPER_PITCH, ACTION_PITCH_VALUE_DOWN);

    /* R1+B en pitch lo consume el status del bloque pitch: NO cierra. */
    EXPECT_ACTION(KEY_R1 | KEY_B, CTX_CHOPPER_PITCH, ACTION_NONE);
    /* R2+A en pitch: consumido por status. */
    EXPECT_ACTION(KEY_R2 | KEY_A, CTX_CHOPPER_PITCH, ACTION_NONE);
    EXPECT_ACTION(KEY_SELECT, CTX_CHOPPER_PITCH, ACTION_NONE);
    EXPECT_ACTION(KEY_R2 | KEY_UP, CTX_CHOPPER_PITCH, ACTION_NONE);
    printf("chopper PITCH: PREVIEW/APPLY, scope, params, values OK\n");
}

static void test_order_equivalence(void) {
    /* Casos donde una tecla extra CAMBIA la accion (fidelidad de prioridad):
     * en trim, A+LEFT edita el inicio; anadir L1 lo hace grueso; quitar A
     * lo convierte en cursor. En main, A+LEFT anade chop. */
    EXPECT_ACTION(KEY_A | KEY_LEFT, CTX_CHOPPER, ACTION_ADD_CHOP);
    EXPECT_ACTION(KEY_A | KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_START_LEFT);
    EXPECT_ACTION(KEY_L1 | KEY_A | KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_START_LEFT_COARSE);
    EXPECT_ACTION(KEY_LEFT, CTX_CHOPPER_TRIM, ACTION_NUDGE_CURSOR_LEFT);
    /* L1+A en main no hace nada; en trim hace snap. */
    EXPECT_ACTION(KEY_L1 | KEY_A, CTX_CHOPPER, ACTION_NONE);
    EXPECT_ACTION(KEY_L1 | KEY_A, CTX_CHOPPER_TRIM, ACTION_SNAP_BOUNDARY_START);
    /* L1+B: main cicla split, trim y pitch lo toman como snap/split. */
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER, ACTION_SPLIT_PARTS);
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER_TRIM, ACTION_SNAP_BOUNDARY_END);
    EXPECT_ACTION(KEY_L1 | KEY_B, CTX_CHOPPER_PITCH, ACTION_SPLIT_PARTS);
    printf("order equivalence: contextos cambian el significado del acorde OK\n");
}

int main(void) {
    test_global();
    test_mixer();
    test_mixer_fx();
    test_chopper_main();
    test_chopper_trim();
    test_chopper_pitch();
    test_order_equivalence();
    if (g_failures != 0) {
        printf("INPUT_POLICY_HOST_TEST: %d FAILURES\n", g_failures);
        return 1;
    }
    printf("INPUT_POLICY_HOST_TEST_OK (golden bindings Bacon 1.2.1)\n");
    return 0;
}