#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
for test_file in "$ROOT/tests/"test_*.py; do python3 "$test_file"; done
bash "$ROOT/tests/host_syntax_check.sh"
bash "$ROOT/tests/run_host_input_policy.sh"
bash "$ROOT/tests/run_host_navigation.sh"
bash "$ROOT/tests/run_host_help_overlay.sh"
bash "$ROOT/tests/run_host_chop_model.sh"
bash "$ROOT/tests/run_host_edit_history.sh"
bash "$ROOT/tests/run_host_pitch_tool.sh"
bash "$ROOT/tests/run_host_preview_service.sh"
bash "$ROOT/tests/run_host_chopper_view.sh"
bash "$ROOT/tests/run_host_chopper_draw.sh"
bash "$ROOT/tests/run_host_chopper_controller.sh"
bash "$ROOT/tests/run_host_fx_pages.sh"
bash "$ROOT/tests/run_host_mixer_meters.sh"
bash "$ROOT/tests/run_host_mixer_menu.sh"
bash "$ROOT/tests/run_host_fx_navigator.sh"
bash "$ROOT/tests/run_host_filterv2.sh"
bash "$ROOT/tests/run_host_delay_reverb_v2.sh"
bash "$ROOT/tests/run_host_compressor_v2.sh"
bash "$ROOT/tests/run_host_unified_fx.sh"
bash "$ROOT/tests/run_host_phrase_grid_edit.sh"
bash "$ROOT/tests/run_host_phrase_undo.sh"
bash "$ROOT/tests/run_host_audio_driver_modes.sh"
bash "$ROOT/tests/run_host_audio_capabilities.sh"
bash "$ROOT/tests/run_host_audio_router.sh"
bash "$ROOT/tests/run_host_audio_backend.sh"
bash "$ROOT/tests/run_host_audio_engine.sh"
bash "$ROOT/tests/run_host_storage_policy.sh"
bash "$ROOT/tests/run_host_action_scenarios.sh"
bash "$ROOT/tests/run_host_bass_synth.sh"
bash "$ROOT/tests/run_host_mixer_vu_chain.sh"
bash "$ROOT/tests/run_host_mixer_64bit_sum.sh"
bash "$ROOT/tests/run_host_master_safety.sh"
bash "$ROOT/tests/run_host_piano_synth.sh"
bash "$ROOT/tests/run_host_eq8_struct.sh"
bash "$ROOT/tests/run_host_eq_sub80.sh"
bash "$ROOT/tests/run_host_analyzer_target.sh"
bash "$ROOT/tests/run_host_fx_stems_capture.sh"
bash "$ROOT/tests/run_host_sample_eq_edit.sh"
bash "$ROOT/tests/run_host_spectrum_analyzer.sh"
bash "$ROOT/tests/run_host_panlaw_comp.sh"
for f in "$ROOT/scripts/"*.sh; do bash -n "$f"; done
for f in otg_u241_common.sh otg_u241_setup_once.sh otg_u241_apply_profile_once.sh otg_u241_shutdown.sh; do sh -n "$ROOT/device/$f"; done
gcc -std=gnu99 -Wall -Wextra -Werror=implicit-function-declaration -fsyntax-only "$ROOT/device/r36s_u2523_usb_audio_io.c"
for forbidden in patches baselines prompts evidence; do [[ ! -e "$ROOT/$forbidden" ]]; done
[[ ! -e "$ROOT/source/tools" ]]
find "$ROOT" -type f \( -iname '*.ttf' -o -iname '*.otf' -o -iname '*.woff' -o -iname '*.woff2' \) -print -quit | grep -q . && { echo 'ERROR: font file found'; exit 1; } || true
echo AUDIT_CLEAN_MAIN_U2523_OK
